---
- name: Copy tool folders and contents to C:\Tool
  ansible.windows.win_copy:
    src: "binaries/{{ item }}/"
    dest: "C:\\Tool\\{{ item }}"
    remote_src: false
    recursive: true
  loop: "{{ tool_subfolders }}"
  register: result
  failed_when: false


- name: Copy README.txt to C:\Tool
  ansible.windows.win_copy:
    src: "README.md"
    dest: "C:\\Tool\\README.md"
    remote_src: false
