---
- name: Check if KapeFiles repo exists
  ansible.windows.win_stat:
    path: C:\Tool\KapeFiles\.git
  register: kapegit

- name: Clone KapeFiles
  ansible.windows.win_shell: |
    git clone --branch master https://github.com/EricZimmerman/KapeFiles.git C:\Tool\KapeFiles
  when: not kapegit.stat.exists

- name: Pull latest KapeFiles
  ansible.windows.win_shell: |
    git -C C:\Tool\KapeFiles pull
  when: kapegit.stat.exists
  register: result
  changed_when: "'Already up to date.' not in result.stdout"

- name: Copy Zimmerman net6 tools into the module folder
  ansible.windows.win_copy:
    src: C:\Tool\Zimmerman\net6\
    dest: C:\Tool\KapeFiles\Modules\bin\
    remote_src: true
  register: net6_copy
  ignore_errors: true
  changed_when: false

- name: Copy Zimmerman net9 tools into the module folder
  ansible.windows.win_copy:
    src: C:\Tool\Zimmerman\net9\
    dest: C:\Tool\KapeFiles\Modules\bin\
    remote_src: true
  when: "'as it does not exist' in net6_copy.msg"
  changed_when: false

- name: Copy binaries/ into Kape/
  ansible.windows.win_copy:
    src: binaries/KapeFiles/
    dest: C:\Tool\KapeFiles
    remote_src: false
    recursive: true
    ignore_errors: true

- name: Check if Hayabusa repo exists
  ansible.windows.win_stat:
    path: C:\Tool\KapeFiles\Modules\bin\hayabusa\.git
  register: hayabusa_git

- name: Clone Hayabusa
  ansible.windows.win_shell: |
    git clone --branch main https://github.com/Yamato-Security/hayabusa.git C:\Tool\KapeFiles\Modules\bin\hayabusa
  when: not hayabusa_git.stat.exists

- name: Pull latest Hayabusa
  ansible.windows.win_shell: |
    git -C C:\Tool\KapeFiles\Modules\bin\hayabusa pull
  when: hayabusa_git.stat.exists
  register: result
  changed_when: "'Already up to date.' not in result.stdout"
