---
- name: Copy Zimmerman net6 tools into the module folder
  ansible.windows.win_copy:
    src: C:\Tool\Zimmerman\net6\
    dest: C:\Tool\KapeFiles\Modules\bin\
    remote_src: true
  register: net6_copy
  ignore_errors: true
  changed_when: false

- name: Copy Zimmerman net9 tools into the module folder
  ansible.windows.win_copy:
    src: C:\Tool\Zimmerman\net9\
    dest: C:\Tool\KapeFiles\Modules\bin\
    remote_src: true
  when: "'as it does not exist' in net6_copy.msg"
  changed_when: false

- name: Copy binaries/ into Kape/
  ansible.windows.win_copy:
    src: binaries/KapeFiles/
    dest: C:\Tool\KapeFiles
    remote_src: false
    recursive: true
    ignore_errors: true
